decorate:main.o Person.o Finery.o TShirts.o Sneakers.o
	g++ -o decorate main.o Person.o Finery.o TShirts.o Sneakers.o
main.o:main.cc
	g++ -g -c main.cc
Person.o:Person.hh Person.cc
	g++ -g -c Person.cc
Finery.o:Finery.hh Finery.cc
	g++ -g -c Finery.cc
TShirts.o:TShirts.hh TShirts.cc
	g++ -g -c TShirts.cc
Sneakers.o:Sneakers.hh Sneakers.cc
	g++ -g -c Sneakers.cc
