facade:main.o Fund.o Stock.o NationalDebt.o
	g++ -o facade main.o Fund.o Stock.o NationalDebt.o
main.o:main.cc
	g++ -g -c main.cc
Fund.o:Fund.hh Fund.cc
	g++ -g -c Fund.cc
Stock.o:Stock.hh Stock.cc
	g++ -g -c Stock.cc
NationalDebt.o:NationalDebt.hh NationalDebt.cc
	g++ -g -c NationalDebt.cc

