leifeng:main.o leifeng.o iFactory.o volunteer.o underGraduate.o underGraduateFactory.o volunteerFactory.o
	g++ -o  leifeng main.o leifeng.o iFactory.o volunteer.o underGraduate.o underGraduateFactory.o volunteerFactory.o
main.o:main.cc
	g++ -c -g main.cc
leifeng.o:leifeng.cc leifeng.hh 
	g++ -c -g leifeng.cc 
iFactory.o:iFactory.cc iFactory.hh 
	g++ -c -g iFactory.cc 
volunteer.o:volunteer.cc volunteer.hh
	g++ -c -g volunteer.cc 
underGraduate.o:underGraduate.cc underGraduate.hh
	g++ -c -g underGraduate.cc 
underGraduateFactory.o:underGraduateFactory.cc underGraduateFactory.hh
	g++ -c -g underGraduateFactory.cc 
volunteerFactory.o:volunteerFactory.cc volunteerFactory.hh
	g++ -c -g volunteerFactory.cc 
