flyweights:main.o User.o WebSite.o ConcreteWebSite.o WebSiteFactory.o
	g++ -o flyweights main.o User.o WebSite.o ConcreteWebSite.o WebSiteFactory.o
main.o:main.cc
	g++ -g -c main.cc
User.o:User.hh User.cc
	g++ -g -c User.cc
WebSite.o:WebSite.hh WebSite.cc
	g++ -g -c WebSite.cc
ConcreteWebSite.o:ConcreteWebSite.hh ConcreteWebSite.cc
	g++ -g -c ConcreteWebSite.cc
WebSiteFactory.o:WebSiteFactory.hh WebSiteFactory.cc
	g++ -g -c WebSiteFactory.cc

