proxy:main.o SchoolGirl.o Pursuit.o Proxy.o IGiveGift.o
	g++ -o proxy main.o SchoolGirl.o Pursuit.o Proxy.o IGiveGift.o
main.o:main.cc
	g++ -g -c main.cc
SchoolGirl.o:SchoolGirl.hh SchoolGirl.cc
	g++ -g -c SchoolGirl.cc
Pursuit.o:Pursuit.hh Pursuit.cc
	g++ -g -c Pursuit.cc
Proxy.o:Proxy.hh Proxy.cc
	g++ -g -c Proxy.cc
IGiveGift.o:IGiveGift.hh IGiveGift.cc
	g++ -g -c IGiveGift.cc
	

